---
plugins:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
exclude_patterns:
  - node_modules/**/*
  - __tests__/**/*
  - __mocks__/**/*
  - output/**/*
  - coverage/**/*
  - .github/**/*
  - lib/**/*
