sudo: false
language: node_js
node_js:
  - '12.7.0'
branches:
  only:
    - master
    - /^v[0-9]+.*$/
cache:
  directories:
    - node_modules
install:
  - npm ci
before_script:
  - npm run lint:fix
script:
  - npm run coveralls
deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_TOKEN'
  skip_cleanup: true
  on:
    tags: true
